// Code generated by ent, DO NOT EDIT.

package person

const (
	// Label holds the string label denoting the person type in the database.
	Label = "person"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "user_id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldSecondName holds the string denoting the second_name field in the database.
	FieldSecondName = "second_name"
	// Table holds the table name of the person in the database.
	Table = "person"
)

// Columns holds all SQL columns for person fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldSecondName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
